version: "3.9"
services:
  lichess:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: lichess-docker:v0.1.0
    environment:
      - API_TOKEN=lip_oWEJVloOyWGv5eY16PTw
      - RATING_TYPE=Puzzles
    volumes:
      - ..:/home/lichess
