name: Build Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file .docker/Dockerfile --tag my-image-name:$(date +%s)
