name: Build and test docker

on:
  push:
    branches: ["master"]
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  docker_run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file .docker/Dockerfile --tag lichess-docker:v0.1.0

      - name: Run the Docker container
        run: docker run -e API_TOKEN=${{ secrets.API_TOKEN }} lichess-docker:v0.1.0 -r Bullet
